/**
 * Generate browser-safe example config from local setup values.
 */

const fs = require("fs");
const path = require("path");

const DEFAULT_EXAMPLE_CONFIG_PATH = path.join("examples", "urthreads-worker-config.js");
const DEFAULT_EXAMPLE_WORKER_URL = "";

function jsString(value) {
  return JSON.stringify(String(value || ""));
}

function normalizeWorkerUrl(value) {
  return String(value || "").trim().replace(/\/+$/, "");
}

function buildExampleWorkerConfigContent(workerUrl, options = {}) {
  const normalizedWorkerUrl = normalizeWorkerUrl(workerUrl || DEFAULT_EXAMPLE_WORKER_URL);
  const generatedBy = options.generatedBy || "urthreads setup";
  return [
    "/*",
    " * Browser-safe Worker config for urthreads examples.",
    ` * Generated by: ${generatedBy}`,
    " * This file does not contain secrets.",
    " */",
    "(function() {",
    "  const params = new URLSearchParams(window.location.search);",
    `  const defaultWorkerUrl = ${jsString(normalizedWorkerUrl)};`,
    "  const storageKey = `urthreads:example:worker:${defaultWorkerUrl || \"default\"}`;",
    "",
    "  function normalizeWorkerUrl(value) {",
    "    return String(value || \"\").trim().replace(/\\/+$/, \"\");",
    "  }",
    "",
    "  function getStoredWorkerUrl() {",
    "    try {",
    "      return window.localStorage.getItem(storageKey) || \"\";",
    "    } catch (error) {",
    "      return \"\";",
    "    }",
    "  }",
    "",
    "  function setStoredWorkerUrl(value) {",
    "    try {",
    "      window.localStorage.setItem(storageKey, value);",
    "    } catch (error) {",
    "      // The current page can still use the query-string Worker URL.",
    "    }",
    "  }",
    "",
    "  function clearStoredWorkerUrl() {",
    "    try {",
    "      window.localStorage.removeItem(storageKey);",
    "    } catch (error) {",
    "      // Ignore storage errors; the page falls back to the generated Worker URL.",
    "    }",
    "  }",
    "",
    "  if (params.get(\"resetWorker\") === \"1\") {",
    "    clearStoredWorkerUrl();",
    "  }",
    "",
    "  const workerParam = params.get(\"worker\");",
    "  if (workerParam) {",
    "    setStoredWorkerUrl(normalizeWorkerUrl(workerParam));",
    "  }",
    "",
    "  const workerUrl = normalizeWorkerUrl(workerParam || getStoredWorkerUrl() || defaultWorkerUrl);",
    "  if (!workerUrl) {",
    "    console.warn(\"[urthreads examples] No Worker URL configured. Run urthreads setup-env, run urthreads env set WORKER_URL <url>, or append ?worker=https://your-worker.workers.dev.\");",
    "    return;",
    "  }",
    "  window.URTHREADS_WORKER = workerUrl;",
    "  window.LIKES_CONFIG = window.LIKES_CONFIG || {};",
    "  window.COMMENTS_CONFIG = window.COMMENTS_CONFIG || {};",
    "  window.LIKES_CONFIG.endpoint = window.LIKES_CONFIG.endpoint || `${workerUrl}/likes`;",
    "  window.COMMENTS_CONFIG.endpoint = window.COMMENTS_CONFIG.endpoint || `${workerUrl}/comments`;",
    "}());",
    "",
  ].join("\n");
}

function writeExampleWorkerConfig(workerUrl, options = {}) {
  const cwd = options.cwd || process.cwd();
  const outputPath = path.resolve(cwd, options.filePath || DEFAULT_EXAMPLE_CONFIG_PATH);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, buildExampleWorkerConfigContent(workerUrl, options), "utf8");
  return outputPath;
}

module.exports = {
  DEFAULT_EXAMPLE_CONFIG_PATH,
  DEFAULT_EXAMPLE_WORKER_URL,
  buildExampleWorkerConfigContent,
  normalizeWorkerUrl,
  writeExampleWorkerConfig,
};
