#!/usr/bin/env node

/**
 * Interactive setup for creating a local .env file.
 *
 * This script intentionally uses only Node built-ins so it can run immediately
 * after cloning the repository.
 */

const fs = require("fs");
const path = require("path");
const readline = require("readline");

const DEFAULTS = {
  databaseName: "likes-and-comments",
  workerName: "likes-and-comments-worker",
  accountId: "",
  apiToken: "",
  databaseId: "",
  workerUrl: "https://likes-and-comments-worker.your-subdomain.workers.dev",
  allowedOrigins: "https://example.com,https://www.example.com",
  allowedOriginsStaging: "https://staging.example.com,http://localhost:3000,http://localhost:8787",
  allowedOriginsProd: "https://example.com,https://www.example.com",
  maxCommentsPerPost: "100",
};

function normalizeUrl(value) {
  return String(value || "").trim().replace(/\/+$/, "");
}

function buildEndpointUrl(workerUrl, endpointPath) {
  const baseUrl = normalizeUrl(workerUrl);
  const cleanPath = String(endpointPath || "").startsWith("/")
    ? endpointPath
    : `/${endpointPath}`;

  return `${baseUrl}${cleanPath}`;
}

function sanitizeOriginList(value) {
  return String(value || "")
    .split(",")
    .map((origin) => origin.trim())
    .filter(Boolean)
    .join(",");
}

function envLine(key, value) {
  return `${key}=${String(value ?? "")}`;
}

function buildEnvContent(config) {
  const workerUrl = normalizeUrl(config.workerUrl || DEFAULTS.workerUrl);
  const allowedOrigins = sanitizeOriginList(
    config.allowedOrigins || DEFAULTS.allowedOrigins
  );
  const allowedOriginsStaging = sanitizeOriginList(
    config.allowedOriginsStaging || DEFAULTS.allowedOriginsStaging
  );
  const allowedOriginsProd = sanitizeOriginList(
    config.allowedOriginsProd || DEFAULTS.allowedOriginsProd
  );

  return [
    "# Cloudflare Likes & Comments environment",
    "# Generated by: cflc setup-env",
    "# Never commit this file.",
    "",
    "# Cloudflare account credentials",
    envLine("CLOUDFLARE_ACCOUNT_ID", config.accountId),
    envLine("CLOUDFLARE_API_TOKEN", config.apiToken),
    "",
    "# D1 database",
    envLine("D1_DATABASE_NAME", config.databaseName || DEFAULTS.databaseName),
    envLine("D1_DATABASE_ID", config.databaseId),
    "",
    "# Worker deployment",
    envLine("WORKER_NAME", config.workerName || DEFAULTS.workerName),
    envLine("WORKER_URL", workerUrl),
    "",
    "# CORS",
    "# Use specific origins in production. Avoid \"*\" unless you are testing.",
    envLine("ALLOWED_ORIGINS", allowedOrigins),
    envLine("ALLOWED_ORIGINS_STAGING", allowedOriginsStaging),
    envLine("ALLOWED_ORIGINS_PROD", allowedOriginsProd),
    "",
    "# Client endpoint URLs",
    envLine("LIKES_ENDPOINT", buildEndpointUrl(workerUrl, "/likes")),
    envLine("COMMENTS_ENDPOINT", buildEndpointUrl(workerUrl, "/comments")),
    "",
    "# Optional runtime settings",
    envLine("MAX_COMMENTS_PER_POST", config.maxCommentsPerPost || DEFAULTS.maxCommentsPerPost),
    "",
  ].join("\n");
}

function showHelp(commandName = "node src/setup-env.js") {
  process.stdout.write(`
Cloudflare Likes & Comments .env Setup

USAGE:
  ${commandName}
  ${commandName} --help

DESCRIPTION:
  Starts an interactive setup that creates a local .env file for Cloudflare,
  D1, Worker deployment, CORS, and client endpoint values.

WHAT YOU NEED:
  - Cloudflare account ID
  - D1 database name and ID
  - Worker URL after deployment, or the URL you plan to use
  - Allowed website origins for CORS

SAFETY:
  - Real .env files are ignored by Git.
  - Existing .env files are not overwritten unless you confirm.

EXAMPLES:
  cflc setup-env
  npm run setup:env

`);
}

function createPrompter(input = process.stdin, output = process.stdout) {
  const rl = readline.createInterface({ input, output });

  function ask(question, defaultValue = "") {
    const suffix = defaultValue ? ` (${defaultValue})` : "";
    return new Promise((resolve) => {
      rl.question(`${question}${suffix}: `, (answer) => {
        const value = answer.trim();
        resolve(value || defaultValue);
      });
    });
  }

  async function confirm(question, defaultValue = true) {
    const label = defaultValue ? "Y/n" : "y/N";
    const answer = String(await ask(`${question} [${label}]`)).toLowerCase();

    if (!answer) return defaultValue;
    return answer === "y" || answer === "yes";
  }

  return {
    ask,
    confirm,
    close: () => rl.close(),
  };
}

async function collectConfig(prompter, output = process.stdout) {
  output.write("\nCloudflare Likes & Comments .env setup\n");
  output.write("This will create a local .env file for deployment and CLI commands.\n\n");

  output.write("Before you start, make sure you have:\n");
  output.write("  1. A Cloudflare account\n");
  output.write("  2. Wrangler installed and authenticated: npm install -g wrangler && wrangler login\n");
  output.write("  3. A D1 database created: wrangler d1 create likes-and-comments\n\n");

  const accountId = await prompter.ask(
    "Cloudflare account ID",
    DEFAULTS.accountId
  );

  output.write("\nCloudflare API token is optional if you use wrangler login locally.\n");
  output.write("If you enter one, it will be written to .env, which is ignored by Git.\n");
  const apiToken = await prompter.ask(
    "Cloudflare API token",
    DEFAULTS.apiToken
  );

  output.write("\nD1 database\n");
  const databaseName = await prompter.ask(
    "D1 database name",
    DEFAULTS.databaseName
  );
  const databaseId = await prompter.ask(
    "D1 database ID",
    DEFAULTS.databaseId
  );

  output.write("\nWorker deployment\n");
  const workerName = await prompter.ask("Worker name", DEFAULTS.workerName);
  const defaultWorkerUrl = DEFAULTS.workerUrl.replace(DEFAULTS.workerName, workerName);
  const workerUrl = await prompter.ask("Worker URL", defaultWorkerUrl);

  output.write("\nCORS origins\n");
  output.write("Use comma-separated origins. Example: https://example.com,https://www.example.com\n");
  const allowedOrigins = await prompter.ask(
    "Allowed origins",
    DEFAULTS.allowedOrigins
  );
  const allowedOriginsStaging = await prompter.ask(
    "Staging allowed origins",
    DEFAULTS.allowedOriginsStaging
  );
  const allowedOriginsProd = await prompter.ask(
    "Production allowed origins",
    DEFAULTS.allowedOriginsProd
  );

  output.write("\nOptional settings\n");
  const maxCommentsPerPost = await prompter.ask(
    "Maximum comments returned per post",
    DEFAULTS.maxCommentsPerPost
  );

  return {
    accountId,
    apiToken,
    databaseName,
    databaseId,
    workerName,
    workerUrl,
    allowedOrigins,
    allowedOriginsStaging,
    allowedOriginsProd,
    maxCommentsPerPost,
  };
}

async function main(argv = process.argv.slice(2), options = {}) {
  const commandName = options.commandName || "node src/setup-env.js";

  if (argv.includes("--help") || argv.includes("-h") || argv[0] === "help") {
    showHelp(commandName);
    return;
  }

  const envPath = path.resolve(process.cwd(), ".env");
  const prompter = createPrompter();

  try {
    if (fs.existsSync(envPath)) {
      const shouldOverwrite = await prompter.confirm(
        ".env already exists. Overwrite it?",
        false
      );

      if (!shouldOverwrite) {
        process.stdout.write("Setup cancelled. Existing .env was left unchanged.\n");
        return;
      }
    }

    const config = await collectConfig(prompter);
    const content = buildEnvContent(config);

    fs.writeFileSync(envPath, content, { encoding: "utf8", mode: 0o600 });

    process.stdout.write("\nCreated .env\n\n");
    process.stdout.write("Next steps:\n");
    process.stdout.write(`  1. Copy config/wrangler.toml.example to wrangler.toml\n`);
    process.stdout.write(`  2. Add your account_id and database_id to wrangler.toml\n`);
    process.stdout.write(`  3. Initialize D1: wrangler d1 execute ${config.databaseName || DEFAULTS.databaseName} --remote --file=src/schema.sql\n`);
    process.stdout.write("  4. Deploy: wrangler deploy\n");
    process.stdout.write("  5. Replace YOUR_WORKER_URL in examples with your deployed Worker URL\n\n");
  } finally {
    prompter.close();
  }
}

if (require.main === module) {
  main(process.argv.slice(2), { commandName: "node src/setup-env.js" }).catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}

module.exports = {
  DEFAULTS,
  buildEndpointUrl,
  buildEnvContent,
  main,
  normalizeUrl,
  sanitizeOriginList,
  showHelp,
};
